# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

repos:
-   repo: local
    hooks:
    -   id: codespell
        name: codespell
        entry: codespell
        types_or: [c, ino, c++, header]
        language: system
