language: c
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/
git:
  depth: false
  quiet: true
env:
  global:
    - PRETTYNAME="Adafruit TinyUSB Library"
    - BSP_PATH="$HOME/.arduino15/packages/adafruit/hardware"
    #- DOXYFILE=$TRAVIS_BUILD_DIR/.doxyfile

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      
before_install:
    - wget -q https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh
    # add tinyusb option for m4
    - sed -i 's/\(m4:speed=120\)/\1,usbstack=tinyusb/g' install.sh
    - source install.sh
    # Remove release code and clone git master of nRF52
    - BSP_VERSION=`eval ls $BSP_PATH/nrf52`
    - rm -rf $BSP_PATH/nrf52/*
    - git clone --quiet https://github.com/adafruit/Adafruit_nRF52_Arduino.git $BSP_PATH/nrf52/$BSP_VERSION
    # Remove release code and clone git master of SAMD
    - BSP_VERSION=`eval ls $BSP_PATH/samd`
    - rm -rf $BSP_PATH/samd/*
    - git clone --quiet https://github.com/adafruit/ArduinoCore-samd.git $BSP_PATH/samd/$BSP_VERSION

install:
    - arduino --install-library "Adafruit SPIFlash","MIDI Library","Adafruit seesaw Library"
    - git clone --quiet https://github.com/adafruit/SdFat.git $HOME/Arduino/libraries/SdFat
    - pip3 install --user adafruit-nrfutil

script:
    - build_m4_platforms
    - build_nrf5x_platforms

# Generate and deploy documentation
after_success:
    - source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/library_check.sh)
    #- source <(curl -SLs  https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/doxy_gen_and_deploy.sh)
